name: twinkling_stars
description: "A customizable twinkling star background for Flutter apps, supporting multi-color and multiple shapes."
version: 1.0.0
homepage: https://github.com/catminifah/twinkling_stars
repository: https://github.com/catminifah/twinkling_stars
issue_tracker: https://github.com/catminifah/twinkling_stars/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

topics:
  - background
  - animation
  - stars
  - flutter
  - ui